### ISSUE TITLE
Flag restriction is not true in README

### ISSUE THREAD

**Issue by beaufortfrancois** [urish/web-lightbulb#1]
Since you've added Origin Trial token, it should work OOTB for everyone in Chrome M53.

**Comment by urish** [comment]
Thanks! Though M52 (Stable channel) still requires the flag, right?

Should I change it to read:

Currently works only with Chrome 53 (Beta Channel) or newer. In Chrome Stable, you will have to enable Web Bluetooth in `chrome://flags` first.

**Comment by beaufortfrancois** [comment]
Yes you're right, M52 still requires flag.
According to https://www.chromium.org/developers/calendar, M53 will be stable around September 6th.

Your new wording works fine with me:

Currently works only with Chrome 53 (Beta Channel) or newer. In Chrome M52, you will have to enable Web Bluetooth in `chrome://flags/#enable-web-bluetooth` first.
