### ISSUE TITLE
Web ble testing

### ISSUE THREAD

**Issue by thiamugb** [urish/web-lightbulb#4]
Hi,
I want to use web ble in my windows  laptop so i don’t know how parameters or what install thing in google chrome to connect a ble device in this navigator.
If i do i scan in a simple web ble scan i don't see ble periphericals i just see bluetooth simple.
So i think that i miss a configuration.
Need help.
Best regards

**Comment by urish** [comment]
Windows is not currently supported in Chrome Stable, but you can get it to work in two ways:

1. Install the latest [Chrome Canary](https://www.google.com/chrome/browser/canary.html), and enable `chrome://flags/#enable-experimental-web-platform-features` flag as explained here: https://github.com/WebBluetoothCG/web-bluetooth/blob/master/implementation-status.md
I haven't tested it myself, but it should be the preferred option.

2. Install and use the [web-bluetooth-polyfill](https://github.com/urish/web-bluetooth-polyfill). This requires Windows 10 version 1703 or newer, and should work with any recent Chrome version. The setup is not very straightfoward, but you can follow the instructions [here](https://github.com/urish/web-bluetooth-polyfill#installation)

Cheers!

**Comment by thiamugb** [comment]
So i see for the 1 not running for me i done then and nothing seeing.
So I want to test the second me aim is just to seeing a peripherals ble in web ble app

**Comment by thiamugb** [comment]
So is possible to use it on mac os x or a phone ? what extensions installed ?

**Comment by urish** [comment]
On mac (and Android) it should work out of the box, without installing anything. You just need Chrome.

**Comment by thiamugb** [comment]
I do a simple scan with your demo to see my ble pycom.
I see nothing ?? and when i do a scan using (n/f connect i see a peripheri)

**Comment by urish** [comment]
This app only works with BLE smart bulbs of this key: https://www.gearbest.com/smart-light-bulb/pp_230349.html

You can use the [acceptAllDevices](https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/requestDevice#Parameters) option of `navigator.bluetooth.requestDevice` to scan for all devices, and then hopefully you device will show up

**Comment by thiamugb** [comment]
So alright i created my simple code in js.
So if i want to use it in my phone samsung I copied the code and when i execute the button is off if i want to use it locally.

**Comment by thiamugb** [comment]
Thank for your help all is done in my mac os x i want to doing this in samsung mobile devise

**Comment by urish** [comment]
Excellent! This should work with Chrome browser on any recent Samsung device, as long as you have Android 6 or newer.

Samsung's own browser has also added Web Bluetooth support, but you will have to install their very latest release (6.4, released last week) for that: https://www.androidpolice.com/2018/02/19/samsung-internet-v6-4-stable-rolls-web-bluetooth-improved-download-manager/

Good luck!
